"""Property-based tests for GPU infrastructure: health check retry, image validity, artifacts.

Tests three correctness properties specified in the design document:

Property 14: Health Check Retry Timing
    For any health check failure sequence, retries SHALL follow exponential
    backoff with delays of 2s, 4s, and 8s (3 retries maximum), and the failure
    report SHALL include attempt count, total elapsed time, and last error received.

Property 15: Generated Image Validity
    For any image generated by the FLUX pipeline via ComfyUI, the output SHALL
    have dimensions of at least 512x512 pixels and valid PNG or JPEG encoding
    (parseable by standard image libraries without error).

Property 16: Artifact Endpoint Correctness
    For any completed stage artifact served via API, the response SHALL have
    HTTP 200, correct Content-Type (image/png or image/jpeg), file size > 1KB,
    and Cache-Control: no-store header.

**Validates: Requirements 17.1, 17.3, 18.3, 19.1, 19.3, 19.4**

Testing framework: Hypothesis (as specified in design document)
"""
from __future__ import annotations

import io
import struct
import time
from dataclasses import dataclass
from typing import Optional

from hypothesis import given, settings, assume, HealthCheck
from hypothesis import strategies as st

# Use a reasonable max_examples for CI performance
_SETTINGS = settings(deadline=None, max_examples=100, suppress_health_check=[HealthCheck.too_slow])


# ---------------------------------------------------------------------------
# Domain models for property testing (no external dependencies needed)
# ---------------------------------------------------------------------------


@dataclass
class HealthCheckResult:
    """Result of a health check with retry logic."""

    success: bool
    attempt_count: int
    total_elapsed_s: float
    last_error: Optional[str]


@dataclass
class ArtifactResponse:
    """Simulated HTTP response for an artifact endpoint."""

    status_code: int
    content_type: str
    body_size: int
    cache_control: Optional[str]


# ---------------------------------------------------------------------------
# Implementation-under-test: Health check retry logic
# ---------------------------------------------------------------------------

# Constants matching the ComfyUI client implementation
MAX_RETRIES = 3
BACKOFF_DELAYS = [2.0, 4.0, 8.0]
INITIAL_TIMEOUT_S = 5.0
RETRY_TIMEOUT_S = 15.0


def compute_health_check_timing(
    failure_sequence: list[bool],
) -> HealthCheckResult:
    """Simulate health check retry timing given a sequence of pass/fail results.

    The failure_sequence represents whether each attempt fails:
    - failure_sequence[0]: initial attempt
    - failure_sequence[1..3]: retry attempts

    Returns the HealthCheckResult with timing and reporting info.

    This mirrors the logic in ComfyUIClient.health_check().
    """
    total_elapsed = 0.0
    last_error: Optional[str] = None

    # Initial attempt
    if not failure_sequence[0]:
        # Initial attempt succeeded
        return HealthCheckResult(
            success=True,
            attempt_count=1,
            total_elapsed_s=0.0,
            last_error=None,
        )
    last_error = "timeout after initial attempt"

    # Retry attempts with exponential backoff
    for retry_idx in range(min(MAX_RETRIES, len(failure_sequence) - 1)):
        delay = BACKOFF_DELAYS[retry_idx]
        total_elapsed += delay

        attempt_fails = failure_sequence[retry_idx + 1]
        if not attempt_fails:
            # This retry succeeded
            return HealthCheckResult(
                success=True,
                attempt_count=retry_idx + 2,  # 1-indexed: initial + retries
                total_elapsed_s=total_elapsed,
                last_error=None,
            )
        last_error = f"timeout after retry {retry_idx + 1}"

    # All retries exhausted
    return HealthCheckResult(
        success=False,
        attempt_count=1 + MAX_RETRIES,
        total_elapsed_s=total_elapsed,
        last_error=last_error,
    )


# ---------------------------------------------------------------------------
# Implementation-under-test: Image validity checking
# ---------------------------------------------------------------------------


def validate_image_dimensions(width: int, height: int) -> bool:
    """Check if image dimensions meet the minimum 512x512 requirement."""
    return width >= 512 and height >= 512


def is_valid_png(data: bytes) -> bool:
    """Check if data is a valid PNG by verifying the magic bytes and IHDR chunk."""
    PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
    if len(data) < 24:
        return False
    if data[:8] != PNG_MAGIC:
        return False
    # IHDR chunk should follow the magic bytes
    # Bytes 8-11: chunk length (should be 13 for IHDR)
    # Bytes 12-15: chunk type (should be "IHDR")
    chunk_type = data[12:16]
    return chunk_type == b"IHDR"


def is_valid_jpeg(data: bytes) -> bool:
    """Check if data is a valid JPEG by verifying SOI and APP0/APP1 markers."""
    if len(data) < 4:
        return False
    # JPEG starts with SOI marker: 0xFF 0xD8
    if data[0:2] != b"\xff\xd8":
        return False
    # Next marker should be APP0 (0xFF 0xE0) or APP1 (0xFF 0xE1) or other valid markers
    if data[2] != 0xFF:
        return False
    return True


def validate_generated_image(data: bytes, width: int, height: int) -> tuple[bool, str]:
    """Validate a generated image meets requirements.

    Returns (valid, reason) tuple.
    Requirements: dimensions >= 512x512, valid PNG or JPEG encoding.
    """
    if not validate_image_dimensions(width, height):
        return False, f"Dimensions {width}x{height} below minimum 512x512"

    if is_valid_png(data) or is_valid_jpeg(data):
        return True, "Valid image"

    return False, "Not valid PNG or JPEG encoding"


# ---------------------------------------------------------------------------
# Implementation-under-test: Artifact endpoint correctness
# ---------------------------------------------------------------------------

VALID_CONTENT_TYPES = frozenset(["image/png", "image/jpeg"])
MIN_ARTIFACT_SIZE = 1024  # 1KB minimum


def validate_artifact_response(response: ArtifactResponse) -> tuple[bool, list[str]]:
    """Validate an artifact endpoint response meets all requirements.

    Checks:
    - HTTP 200 status
    - Content-Type is image/png or image/jpeg
    - Body size > 1KB
    - Cache-Control: no-store header present

    Returns (valid, list_of_failures).
    """
    failures: list[str] = []

    if response.status_code != 200:
        failures.append(f"Expected HTTP 200, got {response.status_code}")

    if response.content_type not in VALID_CONTENT_TYPES:
        failures.append(
            f"Expected Content-Type in {sorted(VALID_CONTENT_TYPES)}, "
            f"got '{response.content_type}'"
        )

    if response.body_size <= MIN_ARTIFACT_SIZE:
        failures.append(
            f"Expected body size > {MIN_ARTIFACT_SIZE} bytes, "
            f"got {response.body_size}"
        )

    if response.cache_control is None or "no-store" not in response.cache_control:
        failures.append(
            f"Expected Cache-Control containing 'no-store', "
            f"got '{response.cache_control}'"
        )

    return (len(failures) == 0, failures)


# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------

# Failure sequences for health check: list of booleans (True=fails, False=succeeds)
# Length 1-4 (1 initial + up to 3 retries)
_failure_sequence_st = st.lists(
    st.booleans(), min_size=1, max_size=4
)

# Image dimensions (positive integers)
_dimension_st = st.integers(min_value=1, max_value=8192)
_valid_dimension_st = st.integers(min_value=512, max_value=8192)
_invalid_dimension_st = st.integers(min_value=1, max_value=511)

# HTTP status codes
_status_code_st = st.sampled_from([200, 201, 301, 400, 404, 500, 502, 503])

# Content-Type values
_content_type_st = st.sampled_from([
    "image/png", "image/jpeg", "text/html", "application/json",
    "application/octet-stream", "image/webp",
])

# Body sizes (in bytes)
_body_size_st = st.integers(min_value=0, max_value=100_000_000)

# Cache-Control header values
_cache_control_st = st.one_of(
    st.none(),
    st.sampled_from([
        "no-store",
        "no-cache",
        "no-store, no-cache",
        "max-age=3600",
        "public, max-age=86400",
        "private, no-store",
    ]),
)

# Error messages for health check failures
_error_message_st = st.sampled_from([
    "Connection refused",
    "timeout",
    "HTTP 503",
    "HTTP 500",
    "VRAM contention",
    "Connection reset by peer",
])


# ---------------------------------------------------------------------------
# Helper: Generate minimal valid PNG bytes
# ---------------------------------------------------------------------------


def _make_png_bytes(width: int, height: int) -> bytes:
    """Generate minimal valid PNG bytes with given dimensions."""
    # PNG magic + IHDR chunk
    magic = b"\x89PNG\r\n\x1a\n"
    # IHDR: 4 bytes width, 4 bytes height, 1 bit depth, 1 color type,
    # 1 compression, 1 filter, 1 interlace = 13 bytes
    ihdr_data = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    ihdr_length = struct.pack(">I", 13)
    ihdr_type = b"IHDR"
    # CRC placeholder (not validated in our check)
    ihdr_crc = b"\x00\x00\x00\x00"
    return magic + ihdr_length + ihdr_type + ihdr_data + ihdr_crc


def _make_jpeg_bytes(size: int = 2048) -> bytes:
    """Generate minimal valid JPEG bytes."""
    # SOI + APP0 marker + padding
    soi = b"\xff\xd8"
    app0_marker = b"\xff\xe0"
    # Fill to requested size
    padding = b"\x00" * max(0, size - 4)
    return soi + app0_marker + padding


# ---------------------------------------------------------------------------
# Property 14: Health Check Retry Timing
# ---------------------------------------------------------------------------


class TestProperty14HealthCheckRetryTiming:
    """**Validates: Requirements 17.1, 17.3**

    For any health check failure sequence, retries SHALL follow exponential
    backoff with delays of 2s, 4s, and 8s (3 retries maximum), and the failure
    report SHALL include attempt count, total elapsed time, and last error received.
    """

    @given(failure_sequence=_failure_sequence_st)
    @_SETTINGS
    def test_max_attempts_is_four(self, failure_sequence: list[bool]) -> None:
        """Total attempts never exceed 1 initial + 3 retries = 4.

        **Validates: Requirements 17.1**
        """
        result = compute_health_check_timing(failure_sequence)
        assert result.attempt_count <= 1 + MAX_RETRIES, (
            f"Attempt count {result.attempt_count} exceeds maximum "
            f"{1 + MAX_RETRIES} for sequence {failure_sequence}"
        )

    @given(failure_sequence=_failure_sequence_st)
    @_SETTINGS
    def test_backoff_timing_is_exponential(
        self, failure_sequence: list[bool]
    ) -> None:
        """Total elapsed time follows 2s + 4s + 8s = 14s max cumulative backoff.

        **Validates: Requirements 17.1**
        """
        result = compute_health_check_timing(failure_sequence)

        # Maximum total backoff delay is sum of all delays: 2 + 4 + 8 = 14
        max_total_backoff = sum(BACKOFF_DELAYS)
        assert result.total_elapsed_s <= max_total_backoff, (
            f"Total elapsed {result.total_elapsed_s:.1f}s exceeds max "
            f"backoff {max_total_backoff:.1f}s"
        )

    @given(failure_sequence=st.lists(st.just(True), min_size=4, max_size=4))
    @_SETTINGS
    def test_all_failures_report_correctly(
        self, failure_sequence: list[bool]
    ) -> None:
        """When all attempts fail, report includes attempt count, elapsed time, and last error.

        **Validates: Requirements 17.3**
        """
        result = compute_health_check_timing(failure_sequence)

        # All failed
        assert result.success is False
        # Total attempts = 1 initial + 3 retries
        assert result.attempt_count == 4
        # Total elapsed = 2 + 4 + 8 = 14s
        assert result.total_elapsed_s == sum(BACKOFF_DELAYS)
        # Last error is reported
        assert result.last_error is not None
        assert len(result.last_error) > 0

    @given(
        num_failures_before_success=st.integers(min_value=0, max_value=3),
    )
    @_SETTINGS
    def test_success_after_n_failures_reports_correct_timing(
        self, num_failures_before_success: int
    ) -> None:
        """When health check succeeds after N failures, timing matches expected backoff.

        **Validates: Requirements 17.1, 17.3**
        """
        # Build a sequence: N failures then 1 success
        failure_sequence = [True] * num_failures_before_success + [False]
        # Pad to max length to ensure we don't go out of bounds
        failure_sequence = failure_sequence + [True] * (4 - len(failure_sequence))

        result = compute_health_check_timing(failure_sequence)

        assert result.success is True
        assert result.attempt_count == num_failures_before_success + 1

        # Expected elapsed: sum of backoff delays for the failures
        # (first failure = initial attempt, no backoff before it)
        if num_failures_before_success == 0:
            expected_elapsed = 0.0
        else:
            expected_elapsed = sum(BACKOFF_DELAYS[:num_failures_before_success])

        assert abs(result.total_elapsed_s - expected_elapsed) < 0.001, (
            f"Expected elapsed {expected_elapsed:.1f}s after "
            f"{num_failures_before_success} failures, got {result.total_elapsed_s:.1f}s"
        )

    @given(failure_sequence=_failure_sequence_st)
    @_SETTINGS
    def test_backoff_delays_are_2_4_8(
        self, failure_sequence: list[bool]
    ) -> None:
        """Exponential backoff delays are exactly 2s, 4s, 8s.

        **Validates: Requirements 17.1**
        """
        # Verify the constants match the spec
        assert BACKOFF_DELAYS == [2.0, 4.0, 8.0], (
            f"Backoff delays {BACKOFF_DELAYS} don't match spec [2, 4, 8]"
        )
        # And max retries is exactly 3
        assert MAX_RETRIES == 3


# ---------------------------------------------------------------------------
# Property 15: Generated Image Validity
# ---------------------------------------------------------------------------


class TestProperty15GeneratedImageValidity:
    """**Validates: Requirements 18.3**

    For any image generated by the FLUX pipeline via ComfyUI, the output SHALL
    have dimensions of at least 512x512 pixels and valid PNG or JPEG encoding
    (parseable by standard image libraries without error).
    """

    @given(
        width=_valid_dimension_st,
        height=_valid_dimension_st,
    )
    @_SETTINGS
    def test_valid_dimensions_pass(self, width: int, height: int) -> None:
        """Images with dimensions >= 512x512 pass the dimension check.

        **Validates: Requirements 18.3**
        """
        assert validate_image_dimensions(width, height) is True, (
            f"Dimensions {width}x{height} should pass (>= 512x512)"
        )

    @given(
        width=_invalid_dimension_st,
        height=_dimension_st,
    )
    @_SETTINGS
    def test_invalid_width_fails(self, width: int, height: int) -> None:
        """Images with width < 512 fail the dimension check.

        **Validates: Requirements 18.3**
        """
        assert validate_image_dimensions(width, height) is False, (
            f"Width {width} < 512 should fail"
        )

    @given(
        width=_dimension_st,
        height=_invalid_dimension_st,
    )
    @_SETTINGS
    def test_invalid_height_fails(self, width: int, height: int) -> None:
        """Images with height < 512 fail the dimension check.

        **Validates: Requirements 18.3**
        """
        assert validate_image_dimensions(width, height) is False, (
            f"Height {height} < 512 should fail"
        )

    @given(
        width=_valid_dimension_st,
        height=_valid_dimension_st,
    )
    @_SETTINGS
    def test_valid_png_with_valid_dimensions_passes(
        self, width: int, height: int
    ) -> None:
        """Valid PNG encoding + valid dimensions = overall pass.

        **Validates: Requirements 18.3**
        """
        png_data = _make_png_bytes(width, height)
        valid, reason = validate_generated_image(png_data, width, height)
        assert valid is True, f"Valid PNG with {width}x{height} should pass: {reason}"

    @given(
        width=_valid_dimension_st,
        height=_valid_dimension_st,
    )
    @_SETTINGS
    def test_valid_jpeg_with_valid_dimensions_passes(
        self, width: int, height: int
    ) -> None:
        """Valid JPEG encoding + valid dimensions = overall pass.

        **Validates: Requirements 18.3**
        """
        jpeg_data = _make_jpeg_bytes(2048)
        valid, reason = validate_generated_image(jpeg_data, width, height)
        assert valid is True, f"Valid JPEG with {width}x{height} should pass: {reason}"

    @given(
        width=_valid_dimension_st,
        height=_valid_dimension_st,
        random_bytes=st.binary(min_size=100, max_size=1000),
    )
    @_SETTINGS
    def test_invalid_encoding_fails(
        self, width: int, height: int, random_bytes: bytes
    ) -> None:
        """Random bytes that are neither PNG nor JPEG fail validation.

        **Validates: Requirements 18.3**
        """
        # Ensure the random bytes don't accidentally look like PNG or JPEG
        assume(not random_bytes.startswith(b"\x89PNG\r\n\x1a\n"))
        assume(not random_bytes.startswith(b"\xff\xd8\xff"))

        valid, reason = validate_generated_image(random_bytes, width, height)
        assert valid is False, (
            f"Random bytes should not pass as valid image: {reason}"
        )
        assert "encoding" in reason.lower() or "not valid" in reason.lower()

    @given(
        width=_invalid_dimension_st,
        height=_invalid_dimension_st,
    )
    @_SETTINGS
    def test_invalid_dimensions_fail_regardless_of_encoding(
        self, width: int, height: int
    ) -> None:
        """Even with valid PNG encoding, undersized dimensions fail.

        **Validates: Requirements 18.3**
        """
        png_data = _make_png_bytes(width, height)
        valid, reason = validate_generated_image(png_data, width, height)
        assert valid is False, (
            f"Dimensions {width}x{height} should fail even with valid PNG"
        )
        assert "512" in reason, f"Failure reason should mention 512: {reason}"


# ---------------------------------------------------------------------------
# Property 16: Artifact Endpoint Correctness
# ---------------------------------------------------------------------------


class TestProperty16ArtifactEndpointCorrectness:
    """**Validates: Requirements 19.1, 19.3, 19.4**

    For any completed stage artifact served via API, the response SHALL have
    HTTP 200, correct Content-Type (image/png or image/jpeg), file size > 1KB,
    and Cache-Control: no-store header.
    """

    @given(
        body_size=st.integers(min_value=1025, max_value=100_000_000),
        content_type=st.sampled_from(["image/png", "image/jpeg"]),
    )
    @_SETTINGS
    def test_correct_response_passes_all_checks(
        self, body_size: int, content_type: str
    ) -> None:
        """A fully correct artifact response passes validation.

        **Validates: Requirements 19.1, 19.3, 19.4**
        """
        response = ArtifactResponse(
            status_code=200,
            content_type=content_type,
            body_size=body_size,
            cache_control="no-store",
        )
        valid, failures = validate_artifact_response(response)
        assert valid is True, f"Correct response should pass: {failures}"
        assert failures == []

    @given(
        status_code=st.sampled_from([201, 301, 400, 404, 500, 502, 503]),
    )
    @_SETTINGS
    def test_non_200_status_fails(self, status_code: int) -> None:
        """Any status code other than 200 fails the check.

        **Validates: Requirements 19.1**
        """
        response = ArtifactResponse(
            status_code=status_code,
            content_type="image/png",
            body_size=2048,
            cache_control="no-store",
        )
        valid, failures = validate_artifact_response(response)
        assert valid is False
        assert any("200" in f for f in failures)

    @given(
        content_type=st.sampled_from([
            "text/html", "application/json", "application/octet-stream",
            "image/webp", "image/gif", "text/plain",
        ]),
    )
    @_SETTINGS
    def test_wrong_content_type_fails(self, content_type: str) -> None:
        """Content-Type other than image/png or image/jpeg fails.

        **Validates: Requirements 19.1**
        """
        response = ArtifactResponse(
            status_code=200,
            content_type=content_type,
            body_size=2048,
            cache_control="no-store",
        )
        valid, failures = validate_artifact_response(response)
        assert valid is False
        assert any("Content-Type" in f for f in failures)

    @given(
        body_size=st.integers(min_value=0, max_value=1024),
    )
    @_SETTINGS
    def test_body_size_leq_1kb_fails(self, body_size: int) -> None:
        """Body size <= 1KB (1024 bytes) fails the size check.

        **Validates: Requirements 19.3**
        """
        response = ArtifactResponse(
            status_code=200,
            content_type="image/png",
            body_size=body_size,
            cache_control="no-store",
        )
        valid, failures = validate_artifact_response(response)
        assert valid is False
        assert any("size" in f.lower() or "1024" in f for f in failures)

    @given(
        cache_control=st.one_of(
            st.none(),
            st.sampled_from([
                "no-cache",
                "max-age=3600",
                "public, max-age=86400",
                "private",
            ]),
        ),
    )
    @_SETTINGS
    def test_missing_no_store_header_fails(
        self, cache_control: Optional[str]
    ) -> None:
        """Cache-Control without 'no-store' fails the header check.

        **Validates: Requirements 19.4**
        """
        response = ArtifactResponse(
            status_code=200,
            content_type="image/png",
            body_size=2048,
            cache_control=cache_control,
        )
        valid, failures = validate_artifact_response(response)
        assert valid is False
        assert any("no-store" in f for f in failures)

    @given(
        cache_control=st.sampled_from([
            "no-store",
            "no-store, no-cache",
            "private, no-store",
            "no-store, max-age=0",
        ]),
    )
    @_SETTINGS
    def test_cache_control_containing_no_store_passes(
        self, cache_control: str
    ) -> None:
        """Cache-Control containing 'no-store' (even with other directives) passes.

        **Validates: Requirements 19.4**
        """
        response = ArtifactResponse(
            status_code=200,
            content_type="image/png",
            body_size=2048,
            cache_control=cache_control,
        )
        valid, failures = validate_artifact_response(response)
        assert valid is True, f"no-store present but failed: {failures}"

    @given(
        status_code=_status_code_st,
        content_type=_content_type_st,
        body_size=_body_size_st,
        cache_control=_cache_control_st,
    )
    @_SETTINGS
    def test_validation_reports_all_failures(
        self,
        status_code: int,
        content_type: str,
        body_size: int,
        cache_control: Optional[str],
    ) -> None:
        """Validation reports ALL failures, not just the first one found.

        **Validates: Requirements 19.1, 19.3, 19.4**
        """
        response = ArtifactResponse(
            status_code=status_code,
            content_type=content_type,
            body_size=body_size,
            cache_control=cache_control,
        )
        valid, failures = validate_artifact_response(response)

        # Count how many individual checks fail
        expected_failure_count = 0
        if status_code != 200:
            expected_failure_count += 1
        if content_type not in VALID_CONTENT_TYPES:
            expected_failure_count += 1
        if body_size <= MIN_ARTIFACT_SIZE:
            expected_failure_count += 1
        if cache_control is None or "no-store" not in cache_control:
            expected_failure_count += 1

        # valid == True iff no failures
        assert valid == (expected_failure_count == 0), (
            f"valid={valid} but expected_failure_count={expected_failure_count}"
        )
        # All failures should be reported
        assert len(failures) == expected_failure_count, (
            f"Expected {expected_failure_count} failure(s), got {len(failures)}: "
            f"{failures}"
        )
