"""Integration tests for V14 Orchestrator with mocked stages.

Tests VRAM-safe stage ordering, fallback chain execution, SSE event emission,
quality classification, and session metadata.

Requirements: 9.1, 9.2, 9.4, 10.4
"""

from __future__ import annotations

import asyncio
import hashlib
import io
import re
import uuid
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import numpy as np
import pytest
from PIL import Image

from src.photo_pipeline.models import (
    DepthResult,
    ScaleResult,
    SceneParseResult,
    SegmentedObject,
    StageResult,
)
from src.photo_pipeline.models_v14 import (
    MaterialPassResult,
    ObjectMeshResult,
    PhysicsClassification,
    RoomShellResult,
    SemanticLabel,
    V14PipelineConfig,
    V14PipelineManifest,
)
from src.photo_pipeline.orchestrator_v14 import (
    INTERFACE_VERSION,
    MAX_OBJECTS,
    V14Orchestrator,
    V14PipelineError,
    V14ValidationError,
)


# ---------------------------------------------------------------------------
# Test Fixtures and Helpers
# ---------------------------------------------------------------------------


def _create_test_png(tmp_path: Path, name: str = "test_source.png") -> Path:
    """Create a simple test PNG image for pipeline input."""
    img = Image.new("RGB", (640, 480), color=(128, 128, 200))
    path = tmp_path / name
    img.save(path, format="PNG")
    return path


def _create_object_png(tmp_path: Path, mask_id: str) -> Path:
    """Create a small RGBA object PNG for a segmented object."""
    img = Image.new("RGBA", (64, 64), color=(200, 100, 50, 255))
    path = tmp_path / f"obj_{mask_id}.png"
    img.save(path, format="PNG")
    return path


def _make_segmented_objects(
    tmp_path: Path, count: int = 3
) -> list[SegmentedObject]:
    """Create a list of mock SegmentedObject instances."""
    objects = []
    for i in range(count):
        mask_id = f"obj_{i:02d}"
        png_path = _create_object_png(tmp_path, mask_id)
        objects.append(
            SegmentedObject(
                mask_id=mask_id,
                bbox=(50 + i * 100, 50, 80, 80),
                area_px=6400,
                centroid_px=(90.0 + i * 100, 90.0),
                object_png_path=png_path,
            )
        )
    return objects


def _make_depth_map(width: int = 640, height: int = 480) -> np.ndarray:
    """Create a valid depth map (float32, all positive/finite values)."""
    # Simulate a room at 2-5m depth
    depth = np.random.uniform(2.0, 5.0, (height, width)).astype(np.float32)
    return depth


def _sha256_of_file(path: Path) -> str:
    """Compute SHA-256 hash of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while chunk := f.read(8192):
            h.update(chunk)
    return h.hexdigest()


@pytest.fixture
def tmp_session_dir(tmp_path: Path) -> Path:
    """Create a temporary session directory."""
    session_dir = tmp_path / "session_test"
    session_dir.mkdir()
    return session_dir


@pytest.fixture
def source_image(tmp_path: Path) -> Path:
    """Create a test source image."""
    return _create_test_png(tmp_path)


@pytest.fixture
def config() -> V14PipelineConfig:
    """Minimal V14 config for testing."""
    return V14PipelineConfig(
        asset_warehouse_enabled=False,
        pass2_enabled=False,
    )


# ---------------------------------------------------------------------------
# Test: Quality classification logic
# ---------------------------------------------------------------------------


class TestQualityClassification:
    """Test the _classify_quality static method.

    Validates: Requirement 9.1 (quality classification in manifest)
    """

    def test_all_hunyuan_is_full(self):
        """All objects generated by Hunyuan3D → quality = 'full'."""
        results = [
            ObjectMeshResult(
                mesh_path=Path("a.glb"), mask_id=f"obj_{i}",
                generation_method="hunyuan3d_v2.1",
                generation_time_s=70.0, face_count=5000,
                vertex_count=2500, has_texture=True,
            )
            for i in range(5)
        ]
        assert V14Orchestrator._classify_quality(results) == "full"

    def test_mixed_methods_is_degraded(self):
        """Mix of Hunyuan3D and Trellis2 → quality = 'degraded'."""
        results = [
            ObjectMeshResult(
                mesh_path=Path("a.glb"), mask_id="obj_0",
                generation_method="hunyuan3d_v2.1",
                generation_time_s=70.0, face_count=5000,
                vertex_count=2500, has_texture=True,
            ),
            ObjectMeshResult(
                mesh_path=Path("b.glb"), mask_id="obj_1",
                generation_method="trellis2",
                generation_time_s=30.0, face_count=3000,
                vertex_count=1500, has_texture=True,
            ),
        ]
        assert V14Orchestrator._classify_quality(results) == "degraded"

    def test_hunyuan_plus_placeholder_is_degraded(self):
        """Mix of Hunyuan3D and placeholder → quality = 'degraded'."""
        results = [
            ObjectMeshResult(
                mesh_path=Path("a.glb"), mask_id="obj_0",
                generation_method="hunyuan3d_v2.1",
                generation_time_s=70.0, face_count=5000,
                vertex_count=2500, has_texture=True,
            ),
            ObjectMeshResult(
                mesh_path=Path("b.glb"), mask_id="obj_1",
                generation_method="placeholder",
                generation_time_s=0.1, face_count=12,
                vertex_count=8, has_texture=False,
            ),
        ]
        assert V14Orchestrator._classify_quality(results) == "degraded"

    def test_all_placeholder_is_minimal(self):
        """All objects are placeholders → quality = 'minimal'."""
        results = [
            ObjectMeshResult(
                mesh_path=Path("a.glb"), mask_id=f"obj_{i}",
                generation_method="placeholder",
                generation_time_s=0.1, face_count=12,
                vertex_count=8, has_texture=False,
            )
            for i in range(4)
        ]
        assert V14Orchestrator._classify_quality(results) == "minimal"

    def test_empty_results_is_minimal(self):
        """Empty mesh results → quality = 'minimal'."""
        assert V14Orchestrator._classify_quality([]) == "minimal"


# ---------------------------------------------------------------------------
# Test: Session metadata
# ---------------------------------------------------------------------------


class TestSessionMetadata:
    """Test session ID, interface version, and source image hash.

    Validates: Requirement 10.4 (unique session ID, source photo SHA-256)
    """

    def test_session_id_is_uuid(self, tmp_path: Path, config: V14PipelineConfig):
        """Session ID auto-generated as valid UUID4."""
        orch = V14Orchestrator(config=config, session_dir=tmp_path / "s1")
        # Validate it parses as UUID
        parsed = uuid.UUID(orch.session_id, version=4)
        assert str(parsed) == orch.session_id

    def test_explicit_session_id_preserved(self, tmp_path: Path, config: V14PipelineConfig):
        """Explicitly provided session_id is preserved."""
        custom_id = "my-custom-session-123"
        orch = V14Orchestrator(
            config=config, session_dir=tmp_path / "s2", session_id=custom_id
        )
        assert orch.session_id == custom_id

    def test_interface_version_is_14(self):
        """INTERFACE_VERSION constant is 14."""
        assert INTERFACE_VERSION == 14

    def test_source_image_hash_is_sha256(self, source_image: Path):
        """_compute_sha256 returns valid SHA-256 hex digest."""
        result = V14Orchestrator._compute_sha256(source_image)
        assert len(result) == 64
        assert all(c in "0123456789abcdef" for c in result)
        # Compare with independent computation
        expected = _sha256_of_file(source_image)
        assert result == expected


# ---------------------------------------------------------------------------
# Test: SSE event emission
# ---------------------------------------------------------------------------


class TestSSEEventEmission:
    """Test that SSE progress events are emitted at stage transitions.

    Validates: Requirement 9.4 (SSE at each stage transition, per-object
    completion, elapsed time, X of N counters)
    """

    @pytest.mark.asyncio
    async def test_events_emitted_in_vram_safe_order(
        self, tmp_path: Path, source_image: Path, config: V14PipelineConfig
    ):
        """Pipeline emits events matching the required stage order."""
        events: list[dict] = []

        async def capture_event(event: dict) -> None:
            events.append(event)

        orch = V14Orchestrator(
            config=config,
            session_dir=tmp_path / "sess",
            event_callback=capture_event,
        )

        # Create mock objects
        objects = _make_segmented_objects(tmp_path, count=2)
        depth_map = _make_depth_map()
        depth_npy_path = tmp_path / "depth.npy"
        np.save(depth_npy_path, depth_map)

        # Mock all external dependencies
        with (
            patch.object(orch, "_check_comfyui_health", new_callable=AsyncMock),
            patch(
                "src.photo_pipeline.orchestrator_v14.SceneParser"
            ) as MockParser,
            patch(
                "src.photo_pipeline.orchestrator_v14.VRAMManager"
            ) as MockVRAM,
            patch(
                "src.photo_pipeline.orchestrator_v14.DepthAnything3Estimator"
            ) as MockDA3,
            patch(
                "src.photo_pipeline.orchestrator_v14.Hunyuan3DV2Generator"
            ) as MockHunyuan,
            patch(
                "src.photo_pipeline.orchestrator_v14.Trellis2Generator"
            ) as MockTrellis,
            patch(
                "src.photo_pipeline.orchestrator_v14.SemanticLabeler"
            ) as MockLabeler,
            patch(
                "src.photo_pipeline.orchestrator_v14.ScaleCalibrator"
            ) as MockScale,
            patch(
                "src.photo_pipeline.orchestrator_v14.RoomShellReconstructor"
            ) as MockRoom,
            patch(
                "src.photo_pipeline.orchestrator_v14.PhysicsClassifier"
            ) as MockPhysics,
        ):
            # Configure VRAM manager mock
            vram_instance = MockVRAM.return_value
            vram_instance.acquire_model = AsyncMock()
            vram_instance.release_model = AsyncMock()
            orch._vram_manager = vram_instance

            # Configure scene parser mock
            parser_instance = MockParser.return_value
            parser_instance.parse = AsyncMock(
                return_value=SceneParseResult(
                    room_plate_path=tmp_path / "room_plate.png",
                    objects=objects,
                    background_mask_path=tmp_path / "bg.png",
                )
            )

            # Configure depth estimator mock
            da3_instance = MockDA3.return_value
            da3_instance.estimate = AsyncMock(
                return_value=DepthResult(
                    depth_map_path=depth_npy_path,
                    normal_map_path=tmp_path / "normals.npy",
                    valid_pixel_ratio=0.95,
                    depth_range_m=(1.5, 6.0),
                )
            )

            # Configure Hunyuan3D mock (succeeds for all objects)
            hunyuan_instance = MockHunyuan.return_value
            hunyuan_instance.generate = AsyncMock(
                side_effect=lambda **kwargs: ObjectMeshResult(
                    mesh_path=tmp_path / f"{kwargs['mask_id']}.glb",
                    mask_id=kwargs["mask_id"],
                    generation_method="hunyuan3d_v2.1",
                    generation_time_s=65.0,
                    face_count=45000,
                    vertex_count=23000,
                    has_texture=True,
                )
            )

            # Configure semantic labeler mock
            labeler_instance = MockLabeler.return_value
            labeler_instance.label = AsyncMock(
                return_value=SemanticLabel(
                    semantic_label="wooden chair",
                    primary_material="wood",
                    category="props",
                    estimated_era="modern",
                    condition="new",
                    is_architectural=False,
                )
            )

            # Configure scale calibrator mock
            scale_instance = MockScale.return_value
            scale_instance.calibrate = MagicMock(
                return_value=ScaleResult(
                    dimensions_m=(0.5, 0.8, 0.5),
                    scale_factor=1.0,
                    confidence=0.9,
                )
            )

            # Configure room shell mock
            room_instance = MockRoom.return_value
            room_instance.reconstruct = MagicMock(
                return_value=RoomShellResult(
                    mesh_path=tmp_path / "room_shell.glb",
                    dimensions_m=(5.0, 2.7, 4.0),
                    vertex_count=50000,
                    face_count=98000,
                    grid_resolution=(400, 300),
                    faces_removed_gradient=120,
                    used_fallback=False,
                )
            )

            # Configure physics classifier mock
            physics_instance = MockPhysics.return_value
            physics_instance.classify = MagicMock(
                return_value=PhysicsClassification(
                    body_mode="DYNAMIC",
                    mass_kg=5.0,
                    volume_m3=0.2,
                    material_density=600.0,
                    friction=0.5,
                    restitution=0.2,
                    can_topple=True,
                    override_reason=None,
                )
            )

            # Run the pipeline
            manifest = await orch.run(source_image)

            # Verify events were emitted
            assert len(events) > 0

            # Extract stage names from events (only 'started' events)
            started_stages = [
                e["stage"]
                for e in events
                if e.get("status") == "started"
            ]

            # Verify VRAM-safe ordering: sam → flux → depth → mesh → room → ...
            expected_order = [
                "sam_segmentation",
                "flux_inpainting",
                "depth_estimation",
                "mesh_generation",
                "room_shell_reconstruction",
                "semantic_labeling",
                "scale_calibration",
                "layout_physics",
                "physics_classification",
                "pass1_materials",
                "world_contract_assembly",
            ]
            assert started_stages == expected_order

    @pytest.mark.asyncio
    async def test_per_object_events_have_counters(
        self, tmp_path: Path, source_image: Path, config: V14PipelineConfig
    ):
        """Per-object mesh completion events include X of N counters."""
        events: list[dict] = []

        async def capture_event(event: dict) -> None:
            events.append(event)

        orch = V14Orchestrator(
            config=config,
            session_dir=tmp_path / "sess2",
            event_callback=capture_event,
        )

        objects = _make_segmented_objects(tmp_path, count=3)
        depth_map = _make_depth_map()
        depth_npy_path = tmp_path / "depth.npy"
        np.save(depth_npy_path, depth_map)

        with (
            patch.object(orch, "_check_comfyui_health", new_callable=AsyncMock),
            patch(
                "src.photo_pipeline.orchestrator_v14.SceneParser"
            ) as MockParser,
            patch(
                "src.photo_pipeline.orchestrator_v14.DepthAnything3Estimator"
            ) as MockDA3,
            patch(
                "src.photo_pipeline.orchestrator_v14.Hunyuan3DV2Generator"
            ) as MockHunyuan,
            patch(
                "src.photo_pipeline.orchestrator_v14.Trellis2Generator"
            ) as MockTrellis,
            patch(
                "src.photo_pipeline.orchestrator_v14.SemanticLabeler"
            ) as MockLabeler,
            patch(
                "src.photo_pipeline.orchestrator_v14.ScaleCalibrator"
            ) as MockScale,
            patch(
                "src.photo_pipeline.orchestrator_v14.RoomShellReconstructor"
            ) as MockRoom,
            patch(
                "src.photo_pipeline.orchestrator_v14.PhysicsClassifier"
            ) as MockPhysics,
        ):
            # Configure mocks (abbreviated — same as above)
            vram_mock = AsyncMock()
            vram_mock.acquire_model = AsyncMock()
            vram_mock.release_model = AsyncMock()
            orch._vram_manager = vram_mock

            parser_instance = MockParser.return_value
            parser_instance.parse = AsyncMock(
                return_value=SceneParseResult(
                    room_plate_path=tmp_path / "room_plate.png",
                    objects=objects,
                    background_mask_path=tmp_path / "bg.png",
                )
            )

            da3_instance = MockDA3.return_value
            da3_instance.estimate = AsyncMock(
                return_value=DepthResult(
                    depth_map_path=depth_npy_path,
                    normal_map_path=tmp_path / "normals.npy",
                    valid_pixel_ratio=0.95,
                    depth_range_m=(1.5, 6.0),
                )
            )

            hunyuan_instance = MockHunyuan.return_value
            hunyuan_instance.generate = AsyncMock(
                side_effect=lambda **kwargs: ObjectMeshResult(
                    mesh_path=tmp_path / f"{kwargs['mask_id']}.glb",
                    mask_id=kwargs["mask_id"],
                    generation_method="hunyuan3d_v2.1",
                    generation_time_s=65.0,
                    face_count=45000,
                    vertex_count=23000,
                    has_texture=True,
                )
            )

            labeler_instance = MockLabeler.return_value
            labeler_instance.label = AsyncMock(
                return_value=SemanticLabel(
                    semantic_label="wooden chair",
                    primary_material="wood",
                    category="props",
                    estimated_era="modern",
                    condition="new",
                    is_architectural=False,
                )
            )

            scale_instance = MockScale.return_value
            scale_instance.calibrate = MagicMock(
                return_value=ScaleResult(
                    dimensions_m=(0.5, 0.8, 0.5),
                    scale_factor=1.0,
                    confidence=0.9,
                )
            )

            room_instance = MockRoom.return_value
            room_instance.reconstruct = MagicMock(
                return_value=RoomShellResult(
                    mesh_path=tmp_path / "room_shell.glb",
                    dimensions_m=(5.0, 2.7, 4.0),
                    vertex_count=50000,
                    face_count=98000,
                    grid_resolution=(400, 300),
                    faces_removed_gradient=120,
                    used_fallback=False,
                )
            )

            physics_instance = MockPhysics.return_value
            physics_instance.classify = MagicMock(
                return_value=PhysicsClassification(
                    body_mode="DYNAMIC",
                    mass_kg=5.0,
                    volume_m3=0.2,
                    material_density=600.0,
                    friction=0.5,
                    restitution=0.2,
                    can_topple=True,
                    override_reason=None,
                )
            )

            manifest = await orch.run(source_image)

            # Filter per-object completion events
            obj_events = [
                e for e in events
                if e.get("status") == "object_completed"
            ]

            assert len(obj_events) == 3
            # Each event has counter fields
            for i, ev in enumerate(obj_events):
                assert ev["objects_completed"] == i + 1
                assert ev["objects_total"] == 3
                assert "elapsed_s" in ev
                assert "generation_time_s" in ev
                assert "mask_id" in ev

    @pytest.mark.asyncio
    async def test_events_include_elapsed_time(
        self, tmp_path: Path, source_image: Path, config: V14PipelineConfig
    ):
        """Every event includes elapsed_s field (non-negative float)."""
        events: list[dict] = []

        async def capture_event(event: dict) -> None:
            events.append(event)

        orch = V14Orchestrator(
            config=config,
            session_dir=tmp_path / "sess3",
            event_callback=capture_event,
        )

        objects = _make_segmented_objects(tmp_path, count=1)
        depth_map = _make_depth_map()
        depth_npy_path = tmp_path / "depth.npy"
        np.save(depth_npy_path, depth_map)

        with (
            patch.object(orch, "_check_comfyui_health", new_callable=AsyncMock),
            patch(
                "src.photo_pipeline.orchestrator_v14.SceneParser"
            ) as MockParser,
            patch(
                "src.photo_pipeline.orchestrator_v14.DepthAnything3Estimator"
            ) as MockDA3,
            patch(
                "src.photo_pipeline.orchestrator_v14.Hunyuan3DV2Generator"
            ) as MockHunyuan,
            patch(
                "src.photo_pipeline.orchestrator_v14.Trellis2Generator"
            ) as MockTrellis,
            patch(
                "src.photo_pipeline.orchestrator_v14.SemanticLabeler"
            ) as MockLabeler,
            patch(
                "src.photo_pipeline.orchestrator_v14.ScaleCalibrator"
            ) as MockScale,
            patch(
                "src.photo_pipeline.orchestrator_v14.RoomShellReconstructor"
            ) as MockRoom,
            patch(
                "src.photo_pipeline.orchestrator_v14.PhysicsClassifier"
            ) as MockPhysics,
        ):
            vram_mock = AsyncMock()
            vram_mock.acquire_model = AsyncMock()
            vram_mock.release_model = AsyncMock()
            orch._vram_manager = vram_mock

            parser_instance = MockParser.return_value
            parser_instance.parse = AsyncMock(
                return_value=SceneParseResult(
                    room_plate_path=tmp_path / "room_plate.png",
                    objects=objects,
                    background_mask_path=tmp_path / "bg.png",
                )
            )
            da3_instance = MockDA3.return_value
            da3_instance.estimate = AsyncMock(
                return_value=DepthResult(
                    depth_map_path=depth_npy_path,
                    normal_map_path=tmp_path / "normals.npy",
                    valid_pixel_ratio=0.95,
                    depth_range_m=(1.5, 6.0),
                )
            )
            hunyuan_instance = MockHunyuan.return_value
            hunyuan_instance.generate = AsyncMock(
                side_effect=lambda **kwargs: ObjectMeshResult(
                    mesh_path=tmp_path / f"{kwargs['mask_id']}.glb",
                    mask_id=kwargs["mask_id"],
                    generation_method="hunyuan3d_v2.1",
                    generation_time_s=65.0,
                    face_count=45000,
                    vertex_count=23000,
                    has_texture=True,
                )
            )
            labeler_instance = MockLabeler.return_value
            labeler_instance.label = AsyncMock(
                return_value=SemanticLabel(
                    semantic_label="wooden chair",
                    primary_material="wood",
                    category="props",
                    estimated_era="modern",
                    condition="new",
                    is_architectural=False,
                )
            )
            scale_instance = MockScale.return_value
            scale_instance.calibrate = MagicMock(
                return_value=ScaleResult(
                    dimensions_m=(0.5, 0.8, 0.5),
                    scale_factor=1.0,
                    confidence=0.9,
                )
            )
            room_instance = MockRoom.return_value
            room_instance.reconstruct = MagicMock(
                return_value=RoomShellResult(
                    mesh_path=tmp_path / "room_shell.glb",
                    dimensions_m=(5.0, 2.7, 4.0),
                    vertex_count=50000,
                    face_count=98000,
                    grid_resolution=(400, 300),
                    faces_removed_gradient=120,
                    used_fallback=False,
                )
            )
            physics_instance = MockPhysics.return_value
            physics_instance.classify = MagicMock(
                return_value=PhysicsClassification(
                    body_mode="DYNAMIC",
                    mass_kg=5.0,
                    volume_m3=0.2,
                    material_density=600.0,
                    friction=0.5,
                    restitution=0.2,
                    can_topple=True,
                    override_reason=None,
                )
            )

            manifest = await orch.run(source_image)

            # ALL events must have elapsed_s >= 0
            for ev in events:
                assert "elapsed_s" in ev
                assert ev["elapsed_s"] >= 0.0


# ---------------------------------------------------------------------------
# Test: VRAM-safe stage ordering
# ---------------------------------------------------------------------------


class TestVRAMSafeOrdering:
    """Test that VRAM acquire/release calls follow the required order.

    Validates: Requirement 9.2 (VRAM-safe stage order)
    """

    @pytest.mark.asyncio
    async def test_model_acquire_release_order(
        self, tmp_path: Path, source_image: Path, config: V14PipelineConfig
    ):
        """Models are acquired and released in the correct VRAM-safe order."""
        vram_calls: list[tuple[str, str]] = []

        async def track_acquire(model_name: str, est_gb: float) -> None:
            vram_calls.append(("acquire", model_name))

        async def track_release() -> None:
            vram_calls.append(("release", ""))

        orch = V14Orchestrator(
            config=config,
            session_dir=tmp_path / "sess_vram",
            event_callback=AsyncMock(),
        )

        objects = _make_segmented_objects(tmp_path, count=2)
        depth_map = _make_depth_map()
        depth_npy_path = tmp_path / "depth.npy"
        np.save(depth_npy_path, depth_map)

        with (
            patch.object(orch, "_check_comfyui_health", new_callable=AsyncMock),
            patch(
                "src.photo_pipeline.orchestrator_v14.SceneParser"
            ) as MockParser,
            patch(
                "src.photo_pipeline.orchestrator_v14.DepthAnything3Estimator"
            ) as MockDA3,
            patch(
                "src.photo_pipeline.orchestrator_v14.Hunyuan3DV2Generator"
            ) as MockHunyuan,
            patch(
                "src.photo_pipeline.orchestrator_v14.Trellis2Generator"
            ) as MockTrellis,
            patch(
                "src.photo_pipeline.orchestrator_v14.SemanticLabeler"
            ) as MockLabeler,
            patch(
                "src.photo_pipeline.orchestrator_v14.ScaleCalibrator"
            ) as MockScale,
            patch(
                "src.photo_pipeline.orchestrator_v14.RoomShellReconstructor"
            ) as MockRoom,
            patch(
                "src.photo_pipeline.orchestrator_v14.PhysicsClassifier"
            ) as MockPhysics,
        ):
            # Set up tracked VRAM manager
            vram_mock = AsyncMock()
            vram_mock.acquire_model = AsyncMock(side_effect=track_acquire)
            vram_mock.release_model = AsyncMock(side_effect=track_release)
            orch._vram_manager = vram_mock

            parser_instance = MockParser.return_value
            parser_instance.parse = AsyncMock(
                return_value=SceneParseResult(
                    room_plate_path=tmp_path / "room_plate.png",
                    objects=objects,
                    background_mask_path=tmp_path / "bg.png",
                )
            )
            da3_instance = MockDA3.return_value
            da3_instance.estimate = AsyncMock(
                return_value=DepthResult(
                    depth_map_path=depth_npy_path,
                    normal_map_path=tmp_path / "normals.npy",
                    valid_pixel_ratio=0.95,
                    depth_range_m=(1.5, 6.0),
                )
            )
            hunyuan_instance = MockHunyuan.return_value
            hunyuan_instance.generate = AsyncMock(
                side_effect=lambda **kwargs: ObjectMeshResult(
                    mesh_path=tmp_path / f"{kwargs['mask_id']}.glb",
                    mask_id=kwargs["mask_id"],
                    generation_method="hunyuan3d_v2.1",
                    generation_time_s=65.0,
                    face_count=45000,
                    vertex_count=23000,
                    has_texture=True,
                )
            )
            labeler_instance = MockLabeler.return_value
            labeler_instance.label = AsyncMock(
                return_value=SemanticLabel(
                    semantic_label="wooden chair",
                    primary_material="wood",
                    category="props",
                    estimated_era="modern",
                    condition="new",
                    is_architectural=False,
                )
            )
            scale_instance = MockScale.return_value
            scale_instance.calibrate = MagicMock(
                return_value=ScaleResult(
                    dimensions_m=(0.5, 0.8, 0.5),
                    scale_factor=1.0,
                    confidence=0.9,
                )
            )
            room_instance = MockRoom.return_value
            room_instance.reconstruct = MagicMock(
                return_value=RoomShellResult(
                    mesh_path=tmp_path / "room_shell.glb",
                    dimensions_m=(5.0, 2.7, 4.0),
                    vertex_count=50000,
                    face_count=98000,
                    grid_resolution=(400, 300),
                    faces_removed_gradient=120,
                    used_fallback=False,
                )
            )
            physics_instance = MockPhysics.return_value
            physics_instance.classify = MagicMock(
                return_value=PhysicsClassification(
                    body_mode="DYNAMIC",
                    mass_kg=5.0,
                    volume_m3=0.2,
                    material_density=600.0,
                    friction=0.5,
                    restitution=0.2,
                    can_topple=True,
                    override_reason=None,
                )
            )

            manifest = await orch.run(source_image)

            # Verify VRAM-safe order:
            # acquire SAM → acquire FLUX → release → acquire DA3 →
            # release → acquire Hunyuan3D → release
            acquire_names = [
                c[1] for c in vram_calls if c[0] == "acquire"
            ]
            assert acquire_names == [
                "sam_vit_h",
                "flux_klein",
                "depth_anything_3",
                "hunyuan3d_v2.1",
            ]

            # Verify releases happen between model transitions
            release_count = sum(1 for c in vram_calls if c[0] == "release")
            # At minimum: FLUX unload, DA3 unload, Hunyuan unload = 3 releases
            assert release_count >= 3


# ---------------------------------------------------------------------------
# Test: Fallback chain (Hunyuan → Trellis2 → placeholder)
# ---------------------------------------------------------------------------


class TestFallbackChain:
    """Test the mesh generation fallback chain.

    Validates: Requirement 9.2 (fallback execution)
    """

    @pytest.mark.asyncio
    async def test_hunyuan_failure_triggers_trellis2(
        self, tmp_path: Path, source_image: Path, config: V14PipelineConfig
    ):
        """When Hunyuan3D fails, Trellis2 is tried as fallback."""
        orch = V14Orchestrator(
            config=config,
            session_dir=tmp_path / "sess_fb",
            event_callback=AsyncMock(),
        )

        objects = _make_segmented_objects(tmp_path, count=1)
        depth_map = _make_depth_map()
        depth_npy_path = tmp_path / "depth.npy"
        np.save(depth_npy_path, depth_map)

        with (
            patch.object(orch, "_check_comfyui_health", new_callable=AsyncMock),
            patch(
                "src.photo_pipeline.orchestrator_v14.SceneParser"
            ) as MockParser,
            patch(
                "src.photo_pipeline.orchestrator_v14.DepthAnything3Estimator"
            ) as MockDA3,
            patch(
                "src.photo_pipeline.orchestrator_v14.Hunyuan3DV2Generator"
            ) as MockHunyuan,
            patch(
                "src.photo_pipeline.orchestrator_v14.Trellis2Generator"
            ) as MockTrellis,
            patch(
                "src.photo_pipeline.orchestrator_v14.SemanticLabeler"
            ) as MockLabeler,
            patch(
                "src.photo_pipeline.orchestrator_v14.ScaleCalibrator"
            ) as MockScale,
            patch(
                "src.photo_pipeline.orchestrator_v14.RoomShellReconstructor"
            ) as MockRoom,
            patch(
                "src.photo_pipeline.orchestrator_v14.PhysicsClassifier"
            ) as MockPhysics,
        ):
            vram_mock = AsyncMock()
            vram_mock.acquire_model = AsyncMock()
            vram_mock.release_model = AsyncMock()
            orch._vram_manager = vram_mock

            parser_instance = MockParser.return_value
            parser_instance.parse = AsyncMock(
                return_value=SceneParseResult(
                    room_plate_path=tmp_path / "room_plate.png",
                    objects=objects,
                    background_mask_path=tmp_path / "bg.png",
                )
            )
            da3_instance = MockDA3.return_value
            da3_instance.estimate = AsyncMock(
                return_value=DepthResult(
                    depth_map_path=depth_npy_path,
                    normal_map_path=tmp_path / "normals.npy",
                    valid_pixel_ratio=0.95,
                    depth_range_m=(1.5, 6.0),
                )
            )

            # Hunyuan FAILS (returns None)
            hunyuan_instance = MockHunyuan.return_value
            hunyuan_instance.generate = AsyncMock(return_value=None)

            # Trellis2 SUCCEEDS
            trellis_instance = MockTrellis.return_value
            trellis_instance.generate = AsyncMock(
                side_effect=lambda **kwargs: ObjectMeshResult(
                    mesh_path=tmp_path / f"{kwargs['mask_id']}_trellis.glb",
                    mask_id=kwargs["mask_id"],
                    generation_method="trellis2",
                    generation_time_s=25.0,
                    face_count=12000,
                    vertex_count=6000,
                    has_texture=True,
                )
            )

            labeler_instance = MockLabeler.return_value
            labeler_instance.label = AsyncMock(
                return_value=SemanticLabel(
                    semantic_label="wooden chair",
                    primary_material="wood",
                    category="props",
                    estimated_era="modern",
                    condition="new",
                    is_architectural=False,
                )
            )
            scale_instance = MockScale.return_value
            scale_instance.calibrate = MagicMock(
                return_value=ScaleResult(
                    dimensions_m=(0.5, 0.8, 0.5),
                    scale_factor=1.0,
                    confidence=0.9,
                )
            )
            room_instance = MockRoom.return_value
            room_instance.reconstruct = MagicMock(
                return_value=RoomShellResult(
                    mesh_path=tmp_path / "room_shell.glb",
                    dimensions_m=(5.0, 2.7, 4.0),
                    vertex_count=50000,
                    face_count=98000,
                    grid_resolution=(400, 300),
                    faces_removed_gradient=120,
                    used_fallback=False,
                )
            )
            physics_instance = MockPhysics.return_value
            physics_instance.classify = MagicMock(
                return_value=PhysicsClassification(
                    body_mode="DYNAMIC",
                    mass_kg=5.0,
                    volume_m3=0.2,
                    material_density=600.0,
                    friction=0.5,
                    restitution=0.2,
                    can_topple=True,
                    override_reason=None,
                )
            )

            manifest = await orch.run(source_image)

            # Should have used trellis2 since hunyuan failed
            assert manifest.objects[0].mesh_method == "trellis2"
            # Quality should be degraded (not all hunyuan)
            assert manifest.quality_classification == "degraded"
            # Trellis2 generator should have been called
            trellis_instance.generate.assert_called_once()

    @pytest.mark.asyncio
    async def test_both_fail_produces_placeholder(
        self, tmp_path: Path, source_image: Path, config: V14PipelineConfig
    ):
        """When both Hunyuan3D and Trellis2 fail, placeholder is generated."""
        orch = V14Orchestrator(
            config=config,
            session_dir=tmp_path / "sess_ph",
            event_callback=AsyncMock(),
        )

        objects = _make_segmented_objects(tmp_path, count=1)
        depth_map = _make_depth_map()
        depth_npy_path = tmp_path / "depth.npy"
        np.save(depth_npy_path, depth_map)

        with (
            patch.object(orch, "_check_comfyui_health", new_callable=AsyncMock),
            patch(
                "src.photo_pipeline.orchestrator_v14.SceneParser"
            ) as MockParser,
            patch(
                "src.photo_pipeline.orchestrator_v14.DepthAnything3Estimator"
            ) as MockDA3,
            patch(
                "src.photo_pipeline.orchestrator_v14.Hunyuan3DV2Generator"
            ) as MockHunyuan,
            patch(
                "src.photo_pipeline.orchestrator_v14.Trellis2Generator"
            ) as MockTrellis,
            patch(
                "src.photo_pipeline.orchestrator_v14.SemanticLabeler"
            ) as MockLabeler,
            patch(
                "src.photo_pipeline.orchestrator_v14.ScaleCalibrator"
            ) as MockScale,
            patch(
                "src.photo_pipeline.orchestrator_v14.RoomShellReconstructor"
            ) as MockRoom,
            patch(
                "src.photo_pipeline.orchestrator_v14.PhysicsClassifier"
            ) as MockPhysics,
            patch(
                "src.photo_pipeline.orchestrator_v14.generate_placeholder"
            ) as mock_gen_placeholder,
        ):
            vram_mock = AsyncMock()
            vram_mock.acquire_model = AsyncMock()
            vram_mock.release_model = AsyncMock()
            orch._vram_manager = vram_mock

            parser_instance = MockParser.return_value
            parser_instance.parse = AsyncMock(
                return_value=SceneParseResult(
                    room_plate_path=tmp_path / "room_plate.png",
                    objects=objects,
                    background_mask_path=tmp_path / "bg.png",
                )
            )
            da3_instance = MockDA3.return_value
            da3_instance.estimate = AsyncMock(
                return_value=DepthResult(
                    depth_map_path=depth_npy_path,
                    normal_map_path=tmp_path / "normals.npy",
                    valid_pixel_ratio=0.95,
                    depth_range_m=(1.5, 6.0),
                )
            )

            # Both generators FAIL
            hunyuan_instance = MockHunyuan.return_value
            hunyuan_instance.generate = AsyncMock(return_value=None)
            trellis_instance = MockTrellis.return_value
            trellis_instance.generate = AsyncMock(return_value=None)

            # Placeholder generator mock
            placeholder_path = tmp_path / "placeholder.glb"
            placeholder_path.write_bytes(b"fake_glb")
            mock_gen_placeholder.return_value = placeholder_path

            labeler_instance = MockLabeler.return_value
            labeler_instance.label = AsyncMock(
                return_value=SemanticLabel(
                    semantic_label="unknown object",
                    primary_material="plastic",
                    category="props",
                    estimated_era="modern",
                    condition="new",
                    is_architectural=False,
                )
            )
            scale_instance = MockScale.return_value
            scale_instance.calibrate = MagicMock(
                return_value=ScaleResult(
                    dimensions_m=(0.5, 0.5, 0.5),
                    scale_factor=1.0,
                    confidence=0.5,
                )
            )
            room_instance = MockRoom.return_value
            room_instance.reconstruct = MagicMock(
                return_value=RoomShellResult(
                    mesh_path=tmp_path / "room_shell.glb",
                    dimensions_m=(5.0, 2.7, 4.0),
                    vertex_count=50000,
                    face_count=98000,
                    grid_resolution=(400, 300),
                    faces_removed_gradient=120,
                    used_fallback=False,
                )
            )
            physics_instance = MockPhysics.return_value
            physics_instance.classify = MagicMock(
                return_value=PhysicsClassification(
                    body_mode="DYNAMIC",
                    mass_kg=1.0,
                    volume_m3=0.125,
                    material_density=950.0,
                    friction=0.5,
                    restitution=0.2,
                    can_topple=True,
                    override_reason=None,
                )
            )

            manifest = await orch.run(source_image)

            # Should be placeholder
            assert manifest.objects[0].mesh_method == "placeholder"
            assert manifest.quality_classification == "minimal"
            # Placeholder generator was called
            mock_gen_placeholder.assert_called_once()


# ---------------------------------------------------------------------------
# Test: Up to 15 objects support
# ---------------------------------------------------------------------------


class TestMaxObjectsSupport:
    """Test support for up to 15 objects.

    Validates: Requirement 9.1 (up to 15 segmented objects)
    """

    @pytest.mark.asyncio
    async def test_15_objects_processed(
        self, tmp_path: Path, source_image: Path, config: V14PipelineConfig
    ):
        """Pipeline handles 15 objects (the maximum supported)."""
        orch = V14Orchestrator(
            config=config,
            session_dir=tmp_path / "sess_15",
            event_callback=AsyncMock(),
        )

        objects = _make_segmented_objects(tmp_path, count=15)
        depth_map = _make_depth_map()
        depth_npy_path = tmp_path / "depth.npy"
        np.save(depth_npy_path, depth_map)

        with (
            patch.object(orch, "_check_comfyui_health", new_callable=AsyncMock),
            patch(
                "src.photo_pipeline.orchestrator_v14.SceneParser"
            ) as MockParser,
            patch(
                "src.photo_pipeline.orchestrator_v14.DepthAnything3Estimator"
            ) as MockDA3,
            patch(
                "src.photo_pipeline.orchestrator_v14.Hunyuan3DV2Generator"
            ) as MockHunyuan,
            patch(
                "src.photo_pipeline.orchestrator_v14.Trellis2Generator"
            ) as MockTrellis,
            patch(
                "src.photo_pipeline.orchestrator_v14.SemanticLabeler"
            ) as MockLabeler,
            patch(
                "src.photo_pipeline.orchestrator_v14.ScaleCalibrator"
            ) as MockScale,
            patch(
                "src.photo_pipeline.orchestrator_v14.RoomShellReconstructor"
            ) as MockRoom,
            patch(
                "src.photo_pipeline.orchestrator_v14.PhysicsClassifier"
            ) as MockPhysics,
        ):
            vram_mock = AsyncMock()
            vram_mock.acquire_model = AsyncMock()
            vram_mock.release_model = AsyncMock()
            orch._vram_manager = vram_mock

            parser_instance = MockParser.return_value
            parser_instance.parse = AsyncMock(
                return_value=SceneParseResult(
                    room_plate_path=tmp_path / "room_plate.png",
                    objects=objects,
                    background_mask_path=tmp_path / "bg.png",
                )
            )
            da3_instance = MockDA3.return_value
            da3_instance.estimate = AsyncMock(
                return_value=DepthResult(
                    depth_map_path=depth_npy_path,
                    normal_map_path=tmp_path / "normals.npy",
                    valid_pixel_ratio=0.95,
                    depth_range_m=(1.5, 6.0),
                )
            )
            hunyuan_instance = MockHunyuan.return_value
            hunyuan_instance.generate = AsyncMock(
                side_effect=lambda **kwargs: ObjectMeshResult(
                    mesh_path=tmp_path / f"{kwargs['mask_id']}.glb",
                    mask_id=kwargs["mask_id"],
                    generation_method="hunyuan3d_v2.1",
                    generation_time_s=65.0,
                    face_count=45000,
                    vertex_count=23000,
                    has_texture=True,
                )
            )
            labeler_instance = MockLabeler.return_value
            labeler_instance.label = AsyncMock(
                return_value=SemanticLabel(
                    semantic_label="wooden chair",
                    primary_material="wood",
                    category="props",
                    estimated_era="modern",
                    condition="new",
                    is_architectural=False,
                )
            )
            scale_instance = MockScale.return_value
            scale_instance.calibrate = MagicMock(
                return_value=ScaleResult(
                    dimensions_m=(0.5, 0.8, 0.5),
                    scale_factor=1.0,
                    confidence=0.9,
                )
            )
            room_instance = MockRoom.return_value
            room_instance.reconstruct = MagicMock(
                return_value=RoomShellResult(
                    mesh_path=tmp_path / "room_shell.glb",
                    dimensions_m=(5.0, 2.7, 4.0),
                    vertex_count=50000,
                    face_count=98000,
                    grid_resolution=(400, 300),
                    faces_removed_gradient=120,
                    used_fallback=False,
                )
            )
            physics_instance = MockPhysics.return_value
            physics_instance.classify = MagicMock(
                return_value=PhysicsClassification(
                    body_mode="DYNAMIC",
                    mass_kg=5.0,
                    volume_m3=0.2,
                    material_density=600.0,
                    friction=0.5,
                    restitution=0.2,
                    can_topple=True,
                    override_reason=None,
                )
            )

            manifest = await orch.run(source_image)

            # All 15 objects should be processed
            assert len(manifest.objects) == 15
            # Hunyuan3D should have been called 15 times
            assert hunyuan_instance.generate.call_count == 15

    @pytest.mark.asyncio
    async def test_more_than_15_objects_capped(
        self, tmp_path: Path, source_image: Path, config: V14PipelineConfig
    ):
        """Pipeline caps processing to MAX_OBJECTS (15) even with more input."""
        orch = V14Orchestrator(
            config=config,
            session_dir=tmp_path / "sess_cap",
            event_callback=AsyncMock(),
        )

        # Create 20 objects (exceeds MAX_OBJECTS)
        objects = _make_segmented_objects(tmp_path, count=20)
        depth_map = _make_depth_map()
        depth_npy_path = tmp_path / "depth.npy"
        np.save(depth_npy_path, depth_map)

        with (
            patch.object(orch, "_check_comfyui_health", new_callable=AsyncMock),
            patch(
                "src.photo_pipeline.orchestrator_v14.SceneParser"
            ) as MockParser,
            patch(
                "src.photo_pipeline.orchestrator_v14.DepthAnything3Estimator"
            ) as MockDA3,
            patch(
                "src.photo_pipeline.orchestrator_v14.Hunyuan3DV2Generator"
            ) as MockHunyuan,
            patch(
                "src.photo_pipeline.orchestrator_v14.Trellis2Generator"
            ) as MockTrellis,
            patch(
                "src.photo_pipeline.orchestrator_v14.SemanticLabeler"
            ) as MockLabeler,
            patch(
                "src.photo_pipeline.orchestrator_v14.ScaleCalibrator"
            ) as MockScale,
            patch(
                "src.photo_pipeline.orchestrator_v14.RoomShellReconstructor"
            ) as MockRoom,
            patch(
                "src.photo_pipeline.orchestrator_v14.PhysicsClassifier"
            ) as MockPhysics,
        ):
            vram_mock = AsyncMock()
            vram_mock.acquire_model = AsyncMock()
            vram_mock.release_model = AsyncMock()
            orch._vram_manager = vram_mock

            parser_instance = MockParser.return_value
            parser_instance.parse = AsyncMock(
                return_value=SceneParseResult(
                    room_plate_path=tmp_path / "room_plate.png",
                    objects=objects,
                    background_mask_path=tmp_path / "bg.png",
                )
            )
            da3_instance = MockDA3.return_value
            da3_instance.estimate = AsyncMock(
                return_value=DepthResult(
                    depth_map_path=depth_npy_path,
                    normal_map_path=tmp_path / "normals.npy",
                    valid_pixel_ratio=0.95,
                    depth_range_m=(1.5, 6.0),
                )
            )
            hunyuan_instance = MockHunyuan.return_value
            hunyuan_instance.generate = AsyncMock(
                side_effect=lambda **kwargs: ObjectMeshResult(
                    mesh_path=tmp_path / f"{kwargs['mask_id']}.glb",
                    mask_id=kwargs["mask_id"],
                    generation_method="hunyuan3d_v2.1",
                    generation_time_s=65.0,
                    face_count=45000,
                    vertex_count=23000,
                    has_texture=True,
                )
            )
            labeler_instance = MockLabeler.return_value
            labeler_instance.label = AsyncMock(
                return_value=SemanticLabel(
                    semantic_label="wooden chair",
                    primary_material="wood",
                    category="props",
                    estimated_era="modern",
                    condition="new",
                    is_architectural=False,
                )
            )
            scale_instance = MockScale.return_value
            scale_instance.calibrate = MagicMock(
                return_value=ScaleResult(
                    dimensions_m=(0.5, 0.8, 0.5),
                    scale_factor=1.0,
                    confidence=0.9,
                )
            )
            room_instance = MockRoom.return_value
            room_instance.reconstruct = MagicMock(
                return_value=RoomShellResult(
                    mesh_path=tmp_path / "room_shell.glb",
                    dimensions_m=(5.0, 2.7, 4.0),
                    vertex_count=50000,
                    face_count=98000,
                    grid_resolution=(400, 300),
                    faces_removed_gradient=120,
                    used_fallback=False,
                )
            )
            physics_instance = MockPhysics.return_value
            physics_instance.classify = MagicMock(
                return_value=PhysicsClassification(
                    body_mode="DYNAMIC",
                    mass_kg=5.0,
                    volume_m3=0.2,
                    material_density=600.0,
                    friction=0.5,
                    restitution=0.2,
                    can_topple=True,
                    override_reason=None,
                )
            )

            manifest = await orch.run(source_image)

            # Capped at MAX_OBJECTS = 15
            assert len(manifest.objects) == MAX_OBJECTS
            assert hunyuan_instance.generate.call_count == MAX_OBJECTS


# ---------------------------------------------------------------------------
# Test: Manifest output correctness
# ---------------------------------------------------------------------------


class TestManifestOutput:
    """Test that the final manifest contains correct session metadata.

    Validates: Requirements 9.1, 10.4
    """

    @pytest.mark.asyncio
    async def test_manifest_has_correct_metadata(
        self, tmp_path: Path, source_image: Path, config: V14PipelineConfig
    ):
        """Manifest contains session_id, interface_version=14, SHA-256 hash."""
        orch = V14Orchestrator(
            config=config,
            session_dir=tmp_path / "sess_meta",
            event_callback=AsyncMock(),
        )

        objects = _make_segmented_objects(tmp_path, count=2)
        depth_map = _make_depth_map()
        depth_npy_path = tmp_path / "depth.npy"
        np.save(depth_npy_path, depth_map)

        with (
            patch.object(orch, "_check_comfyui_health", new_callable=AsyncMock),
            patch(
                "src.photo_pipeline.orchestrator_v14.SceneParser"
            ) as MockParser,
            patch(
                "src.photo_pipeline.orchestrator_v14.DepthAnything3Estimator"
            ) as MockDA3,
            patch(
                "src.photo_pipeline.orchestrator_v14.Hunyuan3DV2Generator"
            ) as MockHunyuan,
            patch(
                "src.photo_pipeline.orchestrator_v14.Trellis2Generator"
            ) as MockTrellis,
            patch(
                "src.photo_pipeline.orchestrator_v14.SemanticLabeler"
            ) as MockLabeler,
            patch(
                "src.photo_pipeline.orchestrator_v14.ScaleCalibrator"
            ) as MockScale,
            patch(
                "src.photo_pipeline.orchestrator_v14.RoomShellReconstructor"
            ) as MockRoom,
            patch(
                "src.photo_pipeline.orchestrator_v14.PhysicsClassifier"
            ) as MockPhysics,
        ):
            vram_mock = AsyncMock()
            vram_mock.acquire_model = AsyncMock()
            vram_mock.release_model = AsyncMock()
            orch._vram_manager = vram_mock

            parser_instance = MockParser.return_value
            parser_instance.parse = AsyncMock(
                return_value=SceneParseResult(
                    room_plate_path=tmp_path / "room_plate.png",
                    objects=objects,
                    background_mask_path=tmp_path / "bg.png",
                )
            )
            da3_instance = MockDA3.return_value
            da3_instance.estimate = AsyncMock(
                return_value=DepthResult(
                    depth_map_path=depth_npy_path,
                    normal_map_path=tmp_path / "normals.npy",
                    valid_pixel_ratio=0.95,
                    depth_range_m=(1.5, 6.0),
                )
            )
            hunyuan_instance = MockHunyuan.return_value
            hunyuan_instance.generate = AsyncMock(
                side_effect=lambda **kwargs: ObjectMeshResult(
                    mesh_path=tmp_path / f"{kwargs['mask_id']}.glb",
                    mask_id=kwargs["mask_id"],
                    generation_method="hunyuan3d_v2.1",
                    generation_time_s=65.0,
                    face_count=45000,
                    vertex_count=23000,
                    has_texture=True,
                )
            )
            labeler_instance = MockLabeler.return_value
            labeler_instance.label = AsyncMock(
                return_value=SemanticLabel(
                    semantic_label="wooden chair",
                    primary_material="wood",
                    category="props",
                    estimated_era="modern",
                    condition="new",
                    is_architectural=False,
                )
            )
            scale_instance = MockScale.return_value
            scale_instance.calibrate = MagicMock(
                return_value=ScaleResult(
                    dimensions_m=(0.5, 0.8, 0.5),
                    scale_factor=1.0,
                    confidence=0.9,
                )
            )
            room_instance = MockRoom.return_value
            room_instance.reconstruct = MagicMock(
                return_value=RoomShellResult(
                    mesh_path=tmp_path / "room_shell.glb",
                    dimensions_m=(5.0, 2.7, 4.0),
                    vertex_count=50000,
                    face_count=98000,
                    grid_resolution=(400, 300),
                    faces_removed_gradient=120,
                    used_fallback=False,
                )
            )
            physics_instance = MockPhysics.return_value
            physics_instance.classify = MagicMock(
                return_value=PhysicsClassification(
                    body_mode="DYNAMIC",
                    mass_kg=5.0,
                    volume_m3=0.2,
                    material_density=600.0,
                    friction=0.5,
                    restitution=0.2,
                    can_topple=True,
                    override_reason=None,
                )
            )

            manifest = await orch.run(source_image)

            # session_id is a valid UUID
            parsed_uuid = uuid.UUID(manifest.session_id, version=4)
            assert str(parsed_uuid) == manifest.session_id

            # interface_version is 14
            assert manifest.interface_version == 14

            # source_image_hash is a valid SHA-256 (64 hex chars)
            assert len(manifest.source_image_hash) == 64
            assert all(
                c in "0123456789abcdef"
                for c in manifest.source_image_hash
            )
            # It matches the actual file hash
            expected_hash = _sha256_of_file(source_image)
            assert manifest.source_image_hash == expected_hash

            # total_duration_s is positive
            assert manifest.total_duration_s > 0.0

            # Quality is "full" (all hunyuan)
            assert manifest.quality_classification == "full"

            # Stages were recorded
            assert len(manifest.stages) > 0
            stage_names = [s.stage_name for s in manifest.stages]
            assert "sam_segmentation" in stage_names
            assert "mesh_generation" in stage_names
            assert "world_contract_assembly" in stage_names
