"""Cloud model test coverage gap discovery for the E2E testing framework.

Submits the current test manifest, WorldContract schema, and QA_Harness API
surface to a cloud reasoning model to identify untested interaction combinations,
uncovered properties, and missing edge cases.

Outputs proposed test cases as executable pytest stubs in tests/e2e/proposed/
with @pytest.mark.proposed markers. Never auto-promotes — requires human review.

Requirements: 25.1–25.5
"""
from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Default cloud model for coverage discovery
DEFAULT_COVERAGE_MODEL = "qwen3-coder:480b-cloud"
FALLBACK_COVERAGE_MODEL = "gpt-oss:120b-cloud"

# Output directory for proposed tests
PROPOSED_TESTS_DIR = Path(__file__).resolve().parent.parent / "proposed"

# Pytest proposed marker
PROPOSED_MARKER = "@pytest.mark.proposed"


@dataclass
class TestManifestEntry:
    """A single test case in the current test manifest.

    Attributes:
        test_name: Fully qualified test name.
        layer: Test layer (visual, scene, accessibility, etc.).
        markers: List of pytest markers on the test.
        description: Brief description from docstring.
    """

    test_name: str
    layer: str
    markers: list[str] = field(default_factory=list)
    description: str = ""


@dataclass
class ProposedTestCase:
    """A proposed test case generated by the cloud model.

    Attributes:
        test_name: Proposed function name.
        description: What the test validates.
        layer: Target test layer.
        rationale: Why this test is needed (coverage gap explanation).
        test_code: The pytest stub code.
        filename: Proposed output filename.
    """

    test_name: str
    description: str
    layer: str
    rationale: str
    test_code: str
    filename: str = ""

    def __post_init__(self):
        if not self.filename:
            # Generate filename from test_name
            safe_name = re.sub(r"[^a-z0-9_]", "_", self.test_name.lower())
            self.filename = f"test_proposed_{safe_name}.py"


@dataclass
class CoverageDiscoveryReport:
    """Report from a coverage discovery analysis.

    Attributes:
        proposed_tests: List of proposed test cases.
        coverage_gaps: List of identified coverage gaps (human-readable).
        model_used: Cloud model that performed the analysis.
        timestamp: ISO timestamp of the analysis.
        manifest_size: Number of existing tests analyzed.
    """

    proposed_tests: list[ProposedTestCase]
    coverage_gaps: list[str] = field(default_factory=list)
    model_used: str = DEFAULT_COVERAGE_MODEL
    timestamp: str = ""
    manifest_size: int = 0

    def to_dict(self) -> dict:
        """Serialize the report to a JSON-compatible dictionary."""
        return {
            "proposed_tests": [
                {
                    "test_name": t.test_name,
                    "description": t.description,
                    "layer": t.layer,
                    "rationale": t.rationale,
                    "filename": t.filename,
                }
                for t in self.proposed_tests
            ],
            "coverage_gaps": self.coverage_gaps,
            "model_used": self.model_used,
            "timestamp": self.timestamp,
            "manifest_size": self.manifest_size,
        }


def collect_test_manifest(tests_dir: Path) -> list[TestManifestEntry]:
    """Scan the test directory and build a manifest of existing tests.

    Args:
        tests_dir: Path to the tests/e2e/ directory.

    Returns:
        List of TestManifestEntry describing all existing test functions.
    """
    manifest: list[TestManifestEntry] = []

    for test_file in sorted(tests_dir.glob("test_*.py")):
        layer = _infer_layer_from_filename(test_file.name)
        try:
            content = test_file.read_text(encoding="utf-8")
            functions = _extract_test_functions(content)
            for func_name, docstring, markers in functions:
                manifest.append(
                    TestManifestEntry(
                        test_name=f"{test_file.stem}::{func_name}",
                        layer=layer,
                        markers=markers,
                        description=docstring,
                    )
                )
        except Exception as exc:
            logger.warning("Could not parse %s: %s", test_file, exc)

    return manifest


def _infer_layer_from_filename(filename: str) -> str:
    """Infer the test layer from the filename."""
    if "visual" in filename:
        return "visual"
    elif "scene" in filename:
        return "scene"
    elif "accessibility" in filename:
        return "accessibility"
    elif "perceptual" in filename or "fidelity" in filename:
        return "perceptual"
    elif "gpu" in filename or "generation" in filename:
        return "gpu"
    elif "vision" in filename:
        return "vision_qa"
    return "other"


def _extract_test_functions(
    source: str,
) -> list[tuple[str, str, list[str]]]:
    """Extract test function names, docstrings, and markers from source code.

    Returns:
        List of (function_name, docstring, markers) tuples.
    """
    results: list[tuple[str, str, list[str]]] = []

    # Simple regex-based extraction (good enough for manifest building)
    func_pattern = re.compile(
        r"(?:(@pytest\.mark\.\w+(?:\(.*?\))?)\s*\n\s*)*"
        r"def\s+(test_\w+)\s*\(",
        re.MULTILINE,
    )

    # Simpler approach: find all test functions and their preceding markers
    lines = source.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith("def test_"):
            func_match = re.match(r"def (test_\w+)\s*\(", line)
            if func_match:
                func_name = func_match.group(1)

                # Look for markers above (up to 5 lines back)
                markers: list[str] = []
                for j in range(max(0, i - 5), i):
                    marker_line = lines[j].strip()
                    marker_match = re.match(r"@pytest\.mark\.(\w+)", marker_line)
                    if marker_match:
                        markers.append(marker_match.group(1))

                # Look for docstring in next line(s)
                docstring = ""
                if i + 1 < len(lines):
                    next_line = lines[i + 1].strip()
                    if next_line.startswith('"""') or next_line.startswith("'''"):
                        docstring = next_line.strip("\"'").strip()

                results.append((func_name, docstring, markers))
        i += 1

    return results


def build_coverage_prompt(
    manifest: list[TestManifestEntry],
    world_contract_schema: str | None = None,
    qa_harness_api: str | None = None,
) -> str:
    """Build a prompt for the cloud model to identify coverage gaps.

    Args:
        manifest: Current test manifest.
        world_contract_schema: Optional WorldContract schema description.
        qa_harness_api: Optional QA_Harness API surface description.

    Returns:
        Prompt string for cloud model submission.
    """
    prompt = """Analyze the following E2E test manifest and identify coverage gaps.

## Current Test Manifest
"""
    # Group tests by layer
    by_layer: dict[str, list[TestManifestEntry]] = {}
    for entry in manifest:
        by_layer.setdefault(entry.layer, []).append(entry)

    for layer, entries in sorted(by_layer.items()):
        prompt += f"\n### {layer.upper()} ({len(entries)} tests)\n"
        for entry in entries:
            markers_str = f" [{', '.join(entry.markers)}]" if entry.markers else ""
            prompt += f"- {entry.test_name}{markers_str}: {entry.description}\n"

    if world_contract_schema:
        prompt += f"\n## WorldContract Schema\n{world_contract_schema}\n"

    if qa_harness_api:
        prompt += f"\n## QA_Harness API\n{qa_harness_api}\n"

    prompt += """
## Task
Identify:
1. Untested interaction combinations (e.g., concurrent actions, state sequences)
2. Uncovered WorldContract properties (fields never validated)
3. Missing edge cases (boundary values, error recovery paths)

## Required Output Format
Respond with ONLY a JSON object:
{
    "coverage_gaps": ["gap description 1", "gap description 2", ...],
    "proposed_tests": [
        {
            "test_name": "test_function_name",
            "description": "What this test validates",
            "layer": "visual|scene|accessibility|perceptual|gpu|vision_qa",
            "rationale": "Why this test is needed"
        }
    ]
}
"""
    return prompt


def parse_coverage_response(
    response_text: str,
) -> tuple[list[ProposedTestCase], list[str]]:
    """Parse the cloud model's coverage discovery response.

    Args:
        response_text: Raw response from the cloud model.

    Returns:
        Tuple of (proposed_tests, coverage_gaps).
    """
    try:
        # Strip markdown fences
        text = response_text.strip()
        if text.startswith("```"):
            lines = text.split("\n")
            text = "\n".join(lines[1:-1]) if lines[-1].strip() == "```" else "\n".join(lines[1:])
            text = text.strip()

        data = json.loads(text)
        coverage_gaps = data.get("coverage_gaps", [])
        proposed_raw = data.get("proposed_tests", [])

        proposed_tests: list[ProposedTestCase] = []
        for item in proposed_raw:
            test_name = item.get("test_name", "")
            if not test_name.startswith("test_"):
                test_name = f"test_{test_name}"

            proposed = ProposedTestCase(
                test_name=test_name,
                description=item.get("description", ""),
                layer=item.get("layer", "scene"),
                rationale=item.get("rationale", ""),
                test_code=generate_test_stub(
                    test_name=test_name,
                    description=item.get("description", ""),
                    layer=item.get("layer", "scene"),
                ),
            )
            proposed_tests.append(proposed)

        return proposed_tests, coverage_gaps

    except (json.JSONDecodeError, ValueError, TypeError) as exc:
        logger.warning("Failed to parse coverage discovery response: %s", exc)
        return [], []


def generate_test_stub(
    test_name: str,
    description: str,
    layer: str,
) -> str:
    """Generate a pytest stub file for a proposed test.

    The stub includes the @pytest.mark.proposed marker and a descriptive
    docstring explaining what the test should validate.

    Args:
        test_name: The test function name.
        description: What the test validates.
        layer: The target test layer.

    Returns:
        Complete pytest file content as a string.
    """
    return f'''"""Proposed test: {description}

Generated by the coverage discovery cloud model.
Requires human review before promotion to the active test suite.

Layer: {layer}
"""
import pytest


{PROPOSED_MARKER}
@pytest.mark.layer("{layer}")
def {test_name}():
    """{description}"""
    # TODO: Implement this test after human review
    # This test was proposed by the cloud model to address a coverage gap.
    pytest.skip("Proposed test — awaiting human review and implementation")
'''


def write_proposed_tests(
    proposed_tests: list[ProposedTestCase],
    output_dir: Path | None = None,
) -> list[Path]:
    """Write proposed test stubs to the proposed/ directory.

    Args:
        proposed_tests: List of proposed test cases with code.
        output_dir: Override output directory (defaults to tests/e2e/proposed/).

    Returns:
        List of paths to written test files.
    """
    target_dir = output_dir or PROPOSED_TESTS_DIR
    target_dir.mkdir(parents=True, exist_ok=True)

    written_paths: list[Path] = []
    for test in proposed_tests:
        output_path = target_dir / test.filename
        # Don't overwrite existing proposed tests
        if output_path.exists():
            logger.info("Skipping %s — already exists", output_path)
            continue

        output_path.write_text(test.test_code, encoding="utf-8")
        written_paths.append(output_path)
        logger.info("Wrote proposed test: %s", output_path)

    return written_paths


def validate_proposed_test_format(file_path: Path) -> bool:
    """Validate that a proposed test file has correct format.

    Checks:
    - File is syntactically valid Python
    - Contains @pytest.mark.proposed marker
    - Is stored in tests/e2e/proposed/ directory
    - Contains at least one test function

    Args:
        file_path: Path to the proposed test file.

    Returns:
        True if the file passes all format checks.
    """
    if not file_path.exists():
        return False

    content = file_path.read_text(encoding="utf-8")

    # Check for proposed marker
    if PROPOSED_MARKER not in content and "pytest.mark.proposed" not in content:
        return False

    # Check for at least one test function
    if not re.search(r"def test_\w+\s*\(", content):
        return False

    # Check syntactic validity
    try:
        compile(content, str(file_path), "exec")
    except SyntaxError:
        return False

    return True
